export type TableConvertPage = {
  slug: string;
  from: string;
  to: string;
  title: string;
};

export const TABLE_CONVERT_PAGES: TableConvertPage[] = [
  { slug: "csv-to-csv", from: "csv", to: "csv", title: "Convert CSV to CSV Online" },
  { slug: "csv-to-html", from: "csv", to: "html", title: "Convert CSV to HTML Table Online" },
  { slug: "csv-to-json", from: "csv", to: "json", title: "Convert CSV to JSON Array Online" },
  { slug: "csv-to-latex", from: "csv", to: "latex", title: "Convert CSV to LaTeX Table Online" },
  { slug: "csv-to-markdown", from: "csv", to: "markdown", title: "Convert CSV to Markdown Table Online" },
  { slug: "csv-to-sql", from: "csv", to: "sql", title: "Convert CSV to Insert SQL Online" },
  { slug: "csv-to-xml", from: "csv", to: "xml", title: "Convert CSV to XML Online" },
  { slug: "csv-to-yaml", from: "csv", to: "yaml", title: "Convert CSV to YAML Configuration Online" },
  { slug: "html-to-csv", from: "html", to: "csv", title: "Convert HTML Table to CSV Online" },
  { slug: "html-to-html", from: "html", to: "html", title: "Convert HTML Table to HTML Table Online" },
  { slug: "html-to-json", from: "html", to: "json", title: "Convert HTML Table to JSON Array Online" },
  { slug: "html-to-latex", from: "html", to: "latex", title: "Convert HTML Table to LaTeX Table Online" },
  { slug: "html-to-markdown", from: "html", to: "markdown", title: "Convert HTML Table to Markdown Table Online" },
  { slug: "html-to-xml", from: "html", to: "xml", title: "Convert HTML Table to XML Online" },
  { slug: "json-to-csv", from: "json", to: "csv", title: "Convert JSON Array to CSV Online" },
  { slug: "json-to-html", from: "json", to: "html", title: "Convert JSON Array to HTML Table Online" },
  { slug: "json-to-json", from: "json", to: "json", title: "Convert JSON Array to JSON Array Online" },
  { slug: "json-to-markdown", from: "json", to: "markdown", title: "Convert JSON Array to Markdown Table Online" },
  { slug: "json-to-sql", from: "json", to: "sql", title: "Convert JSON Array to Insert SQL Online" },
  { slug: "json-to-xml", from: "json", to: "xml", title: "Convert JSON Array to XML Online" },
  { slug: "markdown-to-csv", from: "markdown", to: "csv", title: "Convert Markdown Table to CSV Online" },
  { slug: "markdown-to-html", from: "markdown", to: "html", title: "Convert Markdown Table to HTML Table Online" },
  { slug: "markdown-to-json", from: "markdown", to: "json", title: "Convert Markdown Table to JSON Array Online" },
  { slug: "markdown-to-latex", from: "markdown", to: "latex", title: "Convert Markdown Table to LaTeX Table Online" },
  { slug: "markdown-to-markdown", from: "markdown", to: "markdown", title: "Convert Markdown Table to Markdown Table Online" },
  { slug: "markdown-to-xml", from: "markdown", to: "xml", title: "Convert Markdown Table to XML Online" },
  { slug: "xml-to-csv", from: "xml", to: "csv", title: "Convert XML to CSV Online" },
  { slug: "xml-to-html", from: "xml", to: "html", title: "Convert XML to HTML Table Online" },
  { slug: "xml-to-markdown", from: "xml", to: "markdown", title: "Convert XML to Markdown Table Online" },
  { slug: "xml-to-sql", from: "xml", to: "sql", title: "Convert XML to Insert SQL Online" },
  { slug: "xml-to-xml", from: "xml", to: "xml", title: "Convert XML to XML Online" },
];

export const TABLE_CONVERT_UNSUPPORTED: TableConvertPage[] = [
  { slug: "csv-to-ascii", from: "csv", to: "ascii", title: "Convert CSV to ASCII Text Table Online" },
  { slug: "csv-to-avro", from: "csv", to: "avro", title: "Convert CSV to Avro Schema Online" },
  { slug: "csv-to-excel", from: "csv", to: "excel", title: "Convert CSV to Excel Online" },
  { slug: "csv-to-jpeg", from: "csv", to: "jpeg", title: "Convert CSV to JPEG Image Online" },
  { slug: "csv-to-jsonlines", from: "csv", to: "jsonlines", title: "Convert CSV to JSONLines Format Online" },
  { slug: "csv-to-magic", from: "csv", to: "magic", title: "Magic" },
  { slug: "csv-to-mediawiki", from: "csv", to: "mediawiki", title: "Convert CSV to MediaWiki Table Online" },
  { slug: "csv-to-pandasdataframe", from: "csv", to: "pandasdataframe", title: "Convert CSV to Pandas DataFrame Online" },
  { slug: "csv-to-pdf", from: "csv", to: "pdf", title: "Convert CSV to PDF Table Online" },
  { slug: "csv-to-php", from: "csv", to: "php", title: "Convert CSV to PHP Array Online" },
  { slug: "csv-to-png", from: "csv", to: "png", title: "Convert CSV to PNG Image Online" },
  { slug: "excel-to-ascii", from: "excel", to: "ascii", title: "Convert Excel to ASCII Text..." },
  { slug: "excel-to-bbcode", from: "excel", to: "bbcode", title: "Convert Excel to BBCode Table Online" },
  { slug: "excel-to-csv", from: "excel", to: "csv", title: "Convert Excel to CSV Online" },
  { slug: "excel-to-excel", from: "excel", to: "excel", title: "Convert Excel to Excel Online" },
  { slug: "excel-to-html", from: "excel", to: "html", title: "Convert Excel to HTML Table Online" },
  { slug: "excel-to-jira", from: "excel", to: "jira", title: "Convert Excel to Jira Table Online" },
  { slug: "excel-to-json", from: "excel", to: "json", title: "Convert Excel to JSON Array Online" },
  { slug: "excel-to-jsonlines", from: "excel", to: "jsonlines", title: "JSONLines" },
  { slug: "excel-to-latex", from: "excel", to: "latex", title: "Convert Excel to LaTeX Table Online" },
  { slug: "excel-to-markdown", from: "excel", to: "markdown", title: "Convert Excel to Markdown Table Online" },
  { slug: "excel-to-pandasdataframe", from: "excel", to: "pandasdataframe", title: "Convert Excel to Pandas DataFrame Online" },
  { slug: "excel-to-php", from: "excel", to: "php", title: "PHP" },
  { slug: "excel-to-png", from: "excel", to: "png", title: "Convert Excel to PNG Image Online" },
  { slug: "excel-to-sql", from: "excel", to: "sql", title: "Convert Excel to Insert SQL Online" },
  { slug: "excel-to-xml", from: "excel", to: "xml", title: "Convert Excel to XML Online" },
  { slug: "excel-to-yaml", from: "excel", to: "yaml", title: "Convert Excel to YAML Configuration Online" },
  { slug: "html-to-bbcode", from: "html", to: "bbcode", title: "Convert HTML Table to BBCode Table Online" },
  { slug: "html-to-excel", from: "html", to: "excel", title: "Convert HTML Table to Excel Online" },
  { slug: "html-to-jpeg", from: "html", to: "jpeg", title: "Convert HTML Table to JPEG Image Online" },
  { slug: "html-to-png", from: "html", to: "png", title: "Convert HTML Table to PNG Image Online" },
  { slug: "json-to-avro", from: "json", to: "avro", title: "Convert JSON Array to Avro Schema Online" },
  { slug: "json-to-excel", from: "json", to: "excel", title: "Convert JSON Array to Excel Online" },
  { slug: "json-to-jpeg", from: "json", to: "jpeg", title: "Convert JSON Array to JPEG Image Online" },
  { slug: "json-to-magic", from: "json", to: "magic", title: "Magic" },
  { slug: "json-to-pandasdataframe", from: "json", to: "pandasdataframe", title: "Convert JSON Array to Pandas DataFrame Online" },
  { slug: "json-to-pdf", from: "json", to: "pdf", title: "Convert JSON Array to PDF Table Online" },
  { slug: "json-to-php", from: "json", to: "php", title: "Convert JSON Array to PHP Array Online" },
  { slug: "json-to-png", from: "json", to: "png", title: "Convert JSON Array to PNG Image Online" },
  { slug: "json-to-protobuf", from: "json", to: "protobuf", title: "Convert JSON Array to Protocol Buffers Online" },
  { slug: "latex-to-csv", from: "latex", to: "csv", title: "Convert LaTeX Table to CSV Online" },
  { slug: "latex-to-excel", from: "latex", to: "excel", title: "Convert LaTeX Table to Excel Online" },
  { slug: "latex-to-html", from: "latex", to: "html", title: "Convert LaTeX Table to HTML Table Online" },
  { slug: "latex-to-jpeg", from: "latex", to: "jpeg", title: "Convert LaTeX Table to JPEG Image Online" },
  { slug: "latex-to-latex", from: "latex", to: "latex", title: "LaTeX Table" },
  { slug: "latex-to-markdown", from: "latex", to: "markdown", title: "Convert LaTeX Table to Markdown Table Online" },
  { slug: "latex-to-pdf", from: "latex", to: "pdf", title: "Convert LaTeX Table to PDF Table Online" },
  { slug: "latex-to-png", from: "latex", to: "png", title: "Convert LaTeX Table to PNG Image Online" },
  { slug: "markdown-to-excel", from: "markdown", to: "excel", title: "Convert Markdown Table to Excel Online" },
  { slug: "markdown-to-jira", from: "markdown", to: "jira", title: "Convert Markdown Table to Jira Table Online" },
  { slug: "markdown-to-jpeg", from: "markdown", to: "jpeg", title: "Convert Markdown Table to JPEG Image Online" },
  { slug: "markdown-to-magic", from: "markdown", to: "magic", title: "Magic" },
  { slug: "markdown-to-pandasdataframe", from: "markdown", to: "pandasdataframe", title: "Convert Markdown Table to Pandas DataFrame Online" },
  { slug: "markdown-to-pdf", from: "markdown", to: "pdf", title: "Convert Markdown Table to PDF Table Online" },
  { slug: "markdown-to-png", from: "markdown", to: "png", title: "PNG" },
  { slug: "markdown-to-restructuredtext", from: "markdown", to: "restructuredtext", title: "Convert Markdown Table to reStructuredText Table Online" },
  { slug: "mediawiki-to-csv", from: "mediawiki", to: "csv", title: "Convert MediaWiki Table to CSV Online" },
  { slug: "mysql-to-csv", from: "mysql", to: "csv", title: "Convert MySQL Query Results to CSV Online" },
  { slug: "mysql-to-excel", from: "mysql", to: "excel", title: "Convert MySQL Query Results to Excel Online" },
  { slug: "mysql-to-json", from: "mysql", to: "json", title: "Convert MySQL Query Results to JSON Array Online" },
  { slug: "mysql-to-sql", from: "mysql", to: "sql", title: "Convert MySQL Query Results to Insert SQL Online" },
  { slug: "sql-to-csv", from: "sql", to: "csv", title: "Convert Insert SQL to CSV Online" },
  { slug: "sql-to-excel", from: "sql", to: "excel", title: "Convert Insert SQL to Excel Online" },
  { slug: "sql-to-html", from: "sql", to: "html", title: "Convert Insert SQL to HTML Table Online" },
  { slug: "sql-to-json", from: "sql", to: "json", title: "Convert Insert SQL to JSON Array Online" },
  { slug: "sql-to-pdf", from: "sql", to: "pdf", title: "Convert Insert SQL to PDF Table Online" },
  { slug: "sql-to-sql", from: "sql", to: "sql", title: "Convert Insert SQL to Insert SQL Online" },
  { slug: "sql-to-xml", from: "sql", to: "xml", title: "Convert Insert SQL to XML Online" },
  { slug: "xml-to-excel", from: "xml", to: "excel", title: "Convert XML to Excel Online" },
  { slug: "xml-to-jpeg", from: "xml", to: "jpeg", title: "Convert XML to JPEG Image Online" },
  { slug: "xml-to-pdf", from: "xml", to: "pdf", title: "Convert XML to PDF Table Online" },
  { slug: "xml-to-png", from: "xml", to: "png", title: "Convert XML to PNG Image Online" },
  { slug: "xml-to-restructuredtext", from: "xml", to: "restructuredtext", title: "Convert XML to reStructuredText Table Online" },
];
